### ISSUE TITLE
Uncaught TypeError: thisTblStyle is undefined

### ISSUE THREAD

**Issue by def00111** [meshesha/PPTXjs#11]
https://github.com/meshesha/PPTXjs/blob/45112145f958d379040b4ab6a726bdf83e75bc8e/js/pptxjs.js#L7757

When trying to open: [S-100TSM7_2019_04.07_EN_InteroperabilityScopes_Presentation.pptx](https://github.com/meshesha/PPTXjs/files/6934627/S-100TSM7_2019_04.07_EN_InteroperabilityScopes_Presentation.pptx)

![firefox_4jaVBKZ6Pb](https://user-images.githubusercontent.com/10849366/128261043-2bcac5c5-a252-4873-9a0a-3078efbfd8d8.png)

**Comment by meshesha** [comment]
thank you. 
I'm working on improving the presentation of tables

**Comment by meshesha** [comment]
fixed in v1.21.00
