### ISSUE TITLE
Uncaught TypeError: warpObj.slideResObj[linkID] is undefined

### ISSUE THREAD

**Issue by def00111** [meshesha/PPTXjs#13]
https://github.com/meshesha/PPTXjs/blob/45112145f958d379040b4ab6a726bdf83e75bc8e/js/pptxjs.js#L7667

When trying to open: [Records_Management_Overview_Training.pptx](https://github.com/meshesha/PPTXjs/files/6949642/Records_Management_Overview_Training.pptx)

![firefox_rExOb6f9Ps](https://user-images.githubusercontent.com/10849366/128611581-9568eed6-eb49-4efe-aea1-c494e77601d0.png)

**Comment by def00111** [comment]
http://g21589.github.io/PPTX2HTML/ also has this issue.

![firefox_tyrzFxEuK8](https://user-images.githubusercontent.com/10849366/128633867-cf1df63e-2495-4f16-a90a-0c75a041d4fa.png)

**Comment by meshesha** [comment]
fixed in v1.21.00
