### ISSUE TITLE
Can it convert pptx to Reveal.js-compatible HTML?

### ISSUE THREAD

**Issue by alexwenbj** [meshesha/PPTXjs#2]
Just like PPTX2HTML，Convert PPTX to Reveal.js-compatible format?

**Comment by meshesha** [comment]
i will work on it soon.

**Comment by meshesha** [comment]
yes it is.
[https://pptx.js.org/pages/demo_revealjs.html
](https://pptx.js.org/pages/demo_revealjs.html
)
