### ISSUE TITLE
XSS vulnerability for hyperlinks

### ISSUE THREAD

**Issue by josuaa** [meshesha/PPTXjs#3]
This project has the same vulnerability as described at pptx2html.

Further information:
- https://github.com/g21589/PPTX2HTML/issues/7
- https://dan.lousqui.fr/xss-vulnerability-report-for-pptx2html-en.html

**Comment by meshesha** [comment]
fixed in [ver. 1.10.4](https://github.com/meshesha/PPTXjs/releases/tag/1.10.4)

**Comment by meshesha** [comment]
fixed in ver. 1.10.4
