### ISSUE TITLE
Uncaught TypeError: tbleStylList is undefined

### ISSUE THREAD

**Issue by def00111** [meshesha/PPTXjs#7]
https://github.com/meshesha/PPTXjs/blob/45112145f958d379040b4ab6a726bdf83e75bc8e/js/pptxjs.js#L7741

When trying to open: [JS-News_2020_Kindersport_d.pptx](https://github.com/meshesha/PPTXjs/files/6903368/JS-News_2020_Kindersport_d.pptx)

**Comment by def00111** [comment]
I can open the file with: https://github.com/g21589/PPTX2HTML

**Comment by def00111** [comment]
![firefox_EpOeR7o2YD](https://user-images.githubusercontent.com/10849366/127563008-9d622bb0-7585-42e2-b437-9b6d288b2989.png)

**Comment by meshesha** [comment]
I'm working on improving the presentation of tables

**Comment by meshesha** [comment]
fixed in v1.21.00
