### ISSUE TITLE
Uncaught TypeError: startPoint is undefined

### ISSUE THREAD

**Issue by def00111** [meshesha/PPTXjs#8]
https://github.com/meshesha/PPTXjs/blob/45112145f958d379040b4ab6a726bdf83e75bc8e/js/pptxjs.js#L6837

When trying to open: [9119-3d-cubes-template.pptx](https://github.com/meshesha/PPTXjs/files/6903631/9119-3d-cubes-template.pptx)

![firefox_Sce0VIAQF3](https://user-images.githubusercontent.com/10849366/127566636-c2531486-d824-4563-8917-3921c804f9bf.png)

**Comment by def00111** [comment]
Download link: https://slidehunter.com/download/10642/

**Comment by def00111** [comment]
I can open the file with: https://github.com/g21589/PPTX2HTML

**Comment by meshesha** [comment]
thank you. I'll check it out.

**Comment by meshesha** [comment]
fixed in v1.21.00
