### ISSUE TITLE
Uncaught TypeError: zip.file(...) is null

### ISSUE THREAD

**Issue by def00111** [meshesha/PPTXjs#9]
https://github.com/meshesha/PPTXjs/blob/45112145f958d379040b4ab6a726bdf83e75bc8e/js/pptxjs.js#L423

When trying to open: [5850465.pptx](https://github.com/meshesha/PPTXjs/files/6903892/5850465.pptx)

![firefox_arE1NdidPu](https://user-images.githubusercontent.com/10849366/127572043-5c8cfcb6-fbe0-423d-b65c-e708d6454ab2.png)

Note: I converted the file from ppt to pptx using https://online-umwandeln.de/konvertieren/ppt-in-pptx/

Original file: [5850465.zip](https://github.com/meshesha/PPTXjs/files/6903906/5850465.zip)

**Comment by def00111** [comment]
I can open the file with: https://github.com/g21589/PPTX2HTML

**Comment by meshesha** [comment]
thank you. I'll check it out.

**Comment by meshesha** [comment]
fixed in v1.21.00
